### ISSUE TITLE
Android 8 Adaptive Icon for template apps

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/template-blank-ts#16]
The current templates don't appear to ship an icon for the Android 8 adaptive icon sizing so NativeScript apps installed from the templates look kinda... eh. 😄

<img width="307" alt="android8" src="https://user-images.githubusercontent.com/6006148/29754948-64d28290-8b55-11e7-932f-428218489ebc.png">
 
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://medium.com/google-design/designing-adaptive-icons-515af294c783

**Comment by manoldonev** [comment]
Thanks for the tip, @bradmartin. We will update all templates to take care of the Android 8 adaptive icon sizing problem.

**Comment by manoldonev** [comment]
Icons are now updated to take into account Android 8 adaptive icon sizing.
